### ISSUE TITLE
Call to virDomainCreate failed

### ISSUE THREAD

**Issue by anapolima** [vaggeliskls/windows-in-docker-container#13]
I'm facing this error

```
/root/.vagrant.d/gems/3.1.4/gems/fog-libvirt-0.12.0/lib/fog/libvirt/requests/compute/vm_action.rb:7:in `create': Call to virDomainCreate failed: unable to open '/sys/fs/cgroup/machine/qemu-1-default.libvirt-qemu/': No such file or directory (Libvirt::Error)
```

Have no idea what it could be

**Comment by vaggeliskls** [comment]
Hey @anapolima,

Thanks for your feedback.

Could you please share some information about your system host? I would appreciate details such as your Operating System, architecture, and Docker version.

You could attempt to run the program without the volume, just in case. Here is the code you can use:
```
version: "3.9"

services:
  win10:
    image: ghcr.io/vaggeliskls/windows-in-docker-container:latest
    env_file: .env
    stdin_open: true
    tty: true
    privileged: true
    ports:
      - 3389:3389
```

Please share your results along with any other information that could help us identify the issue.

Thank you!
